// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type SendRequest struct {
	TemplateCode string            `json:"template_code,optional"`
	Receiver     []string          `json:"receiver,optional"`
	Variables    map[string]string `json:"variables,optional"`
	Extra        map[string]string `json:"extra,optional"`
}

type SmsResponse struct {
	TraceID      string `json:"trace_id"`
	MsgID        int64  `json:"msg_id"`
	FailCount    int64  `json:"fail_count"`
	SuccessCount int64  `json:"success_count"`
	Time         int64  `json:"time"`
}
