// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type SendRequest struct {
	TemplateCode string                 `json:"template_code,optional"`
	Receivers    []string               `json:"receivers,optional"`
	Variables    map[string]string      `json:"variables,optional"`
	Extra        map[string]interface{} `json:"extra,optional"`
}

type SendResponse struct {
	TraceID      string `json:"trace_id"`
	BatchNo      string `json:"batch_no"`
	FailCount    int    `json:"fail_count"`
	SuccessCount int    `json:"success_count"`
	Time         int64  `json:"time"`
}
