// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	agetent "chihqiang/msgbox-go/services/agent/api/internal/handler/agetent"
	auth "chihqiang/msgbox-go/services/agent/api/internal/handler/auth"
	channel "chihqiang/msgbox-go/services/agent/api/internal/handler/channel"
	template "chihqiang/msgbox-go/services/agent/api/internal/handler/template"
	"chihqiang/msgbox-go/services/agent/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: agetent.InfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/agent"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: auth.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/agent"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/channel",
				Handler: channel.ChannelQueryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/channel/create",
				Handler: channel.ChannelCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/channel/delete",
				Handler: channel.ChannelDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/channel/status",
				Handler: channel.ChannelStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/channel/update",
				Handler: channel.ChannelUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/vendor/configs",
				Handler: channel.GetVendorConfigsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/agent"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/template",
				Handler: template.TemplateQueryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/template/create",
				Handler: template.TemplateCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/template/delete",
				Handler: template.TemplateDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/template/status",
				Handler: template.TemplateStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/template/update",
				Handler: template.TemplateUpdateHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/agent"),
	)
}
