// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: gateway.proto

package gateway

import (
	"context"

	"chihqiang/msgbox-go/services/gateway/rpc/pb/rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SendRequest  = rpc.SendRequest
	SendResponse = rpc.SendResponse

	Gateway interface {
		Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error)
	}

	defaultGateway struct {
		cli zrpc.Client
	}
)

func NewGateway(cli zrpc.Client) Gateway {
	return &defaultGateway{
		cli: cli,
	}
}

func (m *defaultGateway) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	client := rpc.NewGatewayClient(m.cli.Conn())
	return client.Send(ctx, in, opts...)
}
