// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"chihqiang/msgbox-go/services/gateway/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.BasicAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/send",
					Handler: SendHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/gateway"),
	)
}
