// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: services/gateway/rpc/gateway.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentNo       string                 `protobuf:"bytes,1,opt,name=AgentNo,proto3" json:"AgentNo,omitempty"`
	AgentKey      string                 `protobuf:"bytes,2,opt,name=AgentKey,proto3" json:"AgentKey,omitempty"`
	TemplateCode  string                 `protobuf:"bytes,3,opt,name=TemplateCode,proto3" json:"TemplateCode,omitempty"`
	Receiver      []string               `protobuf:"bytes,4,rep,name=Receiver,proto3" json:"Receiver,omitempty"`
	Variables     map[string]string      `protobuf:"bytes,5,rep,name=Variables,proto3" json:"Variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Extra         map[string]string      `protobuf:"bytes,6,rep,name=Extra,proto3" json:"Extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_services_gateway_rpc_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_gateway_rpc_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_services_gateway_rpc_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *SendRequest) GetAgentNo() string {
	if x != nil {
		return x.AgentNo
	}
	return ""
}

func (x *SendRequest) GetAgentKey() string {
	if x != nil {
		return x.AgentKey
	}
	return ""
}

func (x *SendRequest) GetTemplateCode() string {
	if x != nil {
		return x.TemplateCode
	}
	return ""
}

func (x *SendRequest) GetReceiver() []string {
	if x != nil {
		return x.Receiver
	}
	return nil
}

func (x *SendRequest) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *SendRequest) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type SendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	FailCount     int32                  `protobuf:"varint,2,opt,name=FailCount,proto3" json:"FailCount,omitempty"`
	SuccessCount  int32                  `protobuf:"varint,3,opt,name=SuccessCount,proto3" json:"SuccessCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_services_gateway_rpc_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_gateway_rpc_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_services_gateway_rpc_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *SendResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendResponse) GetFailCount() int32 {
	if x != nil {
		return x.FailCount
	}
	return 0
}

func (x *SendResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

var File_services_gateway_rpc_gateway_proto protoreflect.FileDescriptor

const file_services_gateway_rpc_gateway_proto_rawDesc = "" +
	"\n" +
	"\"services/gateway/rpc/gateway.proto\x12\agateway\"\xf5\x02\n" +
	"\vSendRequest\x12\x18\n" +
	"\aAgentNo\x18\x01 \x01(\tR\aAgentNo\x12\x1a\n" +
	"\bAgentKey\x18\x02 \x01(\tR\bAgentKey\x12\"\n" +
	"\fTemplateCode\x18\x03 \x01(\tR\fTemplateCode\x12\x1a\n" +
	"\bReceiver\x18\x04 \x03(\tR\bReceiver\x12A\n" +
	"\tVariables\x18\x05 \x03(\v2#.gateway.SendRequest.VariablesEntryR\tVariables\x125\n" +
	"\x05Extra\x18\x06 \x03(\v2\x1f.gateway.SendRequest.ExtraEntryR\x05Extra\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"d\n" +
	"\fSendResponse\x12\x12\n" +
	"\x04Code\x18\x01 \x01(\x03R\x04Code\x12\x1c\n" +
	"\tFailCount\x18\x02 \x01(\x05R\tFailCount\x12\"\n" +
	"\fSuccessCount\x18\x03 \x01(\x05R\fSuccessCount2>\n" +
	"\aGateway\x123\n" +
	"\x04Send\x12\x14.gateway.SendRequest\x1a\x15.gateway.SendResponseB\aZ\x05./rpcb\x06proto3"

var (
	file_services_gateway_rpc_gateway_proto_rawDescOnce sync.Once
	file_services_gateway_rpc_gateway_proto_rawDescData []byte
)

func file_services_gateway_rpc_gateway_proto_rawDescGZIP() []byte {
	file_services_gateway_rpc_gateway_proto_rawDescOnce.Do(func() {
		file_services_gateway_rpc_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_gateway_rpc_gateway_proto_rawDesc), len(file_services_gateway_rpc_gateway_proto_rawDesc)))
	})
	return file_services_gateway_rpc_gateway_proto_rawDescData
}

var file_services_gateway_rpc_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_services_gateway_rpc_gateway_proto_goTypes = []any{
	(*SendRequest)(nil),  // 0: gateway.SendRequest
	(*SendResponse)(nil), // 1: gateway.SendResponse
	nil,                  // 2: gateway.SendRequest.VariablesEntry
	nil,                  // 3: gateway.SendRequest.ExtraEntry
}
var file_services_gateway_rpc_gateway_proto_depIdxs = []int32{
	2, // 0: gateway.SendRequest.Variables:type_name -> gateway.SendRequest.VariablesEntry
	3, // 1: gateway.SendRequest.Extra:type_name -> gateway.SendRequest.ExtraEntry
	0, // 2: gateway.Gateway.Send:input_type -> gateway.SendRequest
	1, // 3: gateway.Gateway.Send:output_type -> gateway.SendResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_services_gateway_rpc_gateway_proto_init() }
func file_services_gateway_rpc_gateway_proto_init() {
	if File_services_gateway_rpc_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_gateway_rpc_gateway_proto_rawDesc), len(file_services_gateway_rpc_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_gateway_rpc_gateway_proto_goTypes,
		DependencyIndexes: file_services_gateway_rpc_gateway_proto_depIdxs,
		MessageInfos:      file_services_gateway_rpc_gateway_proto_msgTypes,
	}.Build()
	File_services_gateway_rpc_gateway_proto = out.File
	file_services_gateway_rpc_gateway_proto_goTypes = nil
	file_services_gateway_rpc_gateway_proto_depIdxs = nil
}
