// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ChannelCreateReq struct {
	Code         string            `json:"code,optional"`
	Name         string            `json:"name,optional"`
	ProviderCode string            `json:"provider_code"`
	Endpoint     string            `json:"endpoint,optional"`
	Config       map[string]string `json:"config,omitempty"`
	Status       bool              `json:"status,omitempty"`
}

type ChannelItemResp struct {
	ID           int64             `json:"id"`
	AgentID      int64             `json:"agent_id"`
	Code         string            `json:"code"`
	Name         string            `json:"name"`
	ProviderCode string            `json:"provider_code"`
	Endpoint     string            `json:"endpoint"`
	Config       map[string]string `json:"config"`
	Status       bool              `json:"status"`
	CreatedAt    string            `json:"created_at"`
	UpdatedAt    string            `json:"updated_at"`
}

type ChannelQueryReq struct {
	PaginationReq
	ID int64 `json:"id,optional"`
}

type ChannelQueryResp struct {
	Total int64             `json:"total"`
	Data  []ChannelItemResp `json:"data"`
}

type ChannelUpdateReq struct {
	ID           int64             `json:"id"`
	Name         *string           `json:"name,optional,omitempty"`
	ProviderCode *string           `json:"provider_code,optional,omitempty"`
	Endpoint     *string           `json:"endpoint,optional,omitempty"`
	Config       map[string]string `json:"config,optional,omitempty"`
	Status       *bool             `json:"status,optional,omitempty"`
}

type IDReq struct {
	ID int64 `json:"id" validate:"required"`
}

type IDStatusReq struct {
	ID     int64 `json:"id" validate:"required"`
	Status bool  `json:"status"`
}

type LoginReq struct {
	Email    string `json:"email" validate:"email"`
	Password string `json:"password" validate:"required"`
}

type LoginResp struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	Token     string `json:"token"`
	ExpiresIn int64  `json:"expires_in"`
}

type PaginationReq struct {
	Page int `json:"page,default=1"`
	Size int `json:"size,default=10"`
}

type TemplateCreateReq struct {
	ChannelID   []int64 `json:"channel_id"`
	Code        string  `json:"code"`
	VendorCode  string  `json:"vendor_code,optional,omitempty"`
	Signature   string  `json:"signature,optional,omitempty"`
	Content     string  `json:"content"`
	ContentType int     `json:"content_type"`
	Status      bool    `json:"status"`
}

type TemplateItemResp struct {
	ID               int64   `json:"id"`
	AgentID          int64   `json:"agent_id"`
	Code             string  `json:"code"`
	VendorCode       string  `json:"vendor_code"`
	Signature        string  `json:"signature"`
	Content          string  `json:"content"`
	ContentType      int     `json:"content_type"`
	ContentTypeTitle string  `json:"content_type_title"`
	Status           bool    `json:"status"`
	UsedCount        int64   `json:"used_count"`
	CreatedAt        string  `json:"created_at"`
	UpdatedAt        string  `json:"updated_at"`
	ChannelID        []int64 `json:"channel_id"`
}

type TemplateQueryReq struct {
	PaginationReq
	ID *int64 `json:"id,optional"`
}

type TemplateQueryResp struct {
	Total int64              `json:"total"`
	Data  []TemplateItemResp `json:"data"`
}

type TemplateUpdateReq struct {
	ID          int64   `json:"id"`
	ChannelID   []int64 `json:"channel_id"`
	VendorCode  *string `json:"vendor_code,optional,omitempty"`
	Signature   *string `json:"signature,optional,omitempty"`
	Content     *string `json:"content,optional,omitempty"`
	ContentType *int    `json:"content_type,optional,omitempty"`
	Status      *bool   `json:"status,optional,omitempty"`
}
