// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ChannelCreateReq struct {
	Code       string                 `json:"code,optional"`
	Name       string                 `json:"name,optional"`
	VendorName string                 `json:"vendor_name"`
	Config     map[string]interface{} `json:"config,omitempty"`
	Status     bool                   `json:"status,omitempty"`
}

type ChannelItemResp struct {
	ID         int64                  `json:"id"`
	AgentID    int64                  `json:"agent_id"`
	Code       string                 `json:"code"`
	Name       string                 `json:"name"`
	VendorName string                 `json:"vendor_name"`
	Config     map[string]interface{} `json:"config"`
	Status     bool                   `json:"status"`
	CreatedAt  string                 `json:"created_at"`
	UpdatedAt  string                 `json:"updated_at"`
}

type ChannelQueryReq struct {
	PaginationReq
	ID       int64  `json:"id,optional"`
	Keywords string `json:"keywords,optional"`
}

type ChannelQueryResp struct {
	Total int64             `json:"total"`
	Data  []ChannelItemResp `json:"data"`
}

type ChannelUpdateReq struct {
	ID         int64                  `json:"id"`
	Name       *string                `json:"name,optional,omitempty"`
	VendorName *string                `json:"vendor_name,optional,omitempty"`
	Config     map[string]interface{} `json:"config,optional,omitempty"`
	Status     *bool                  `json:"status,optional,omitempty"`
}

type FormField struct {
	Type        string `json:"type"`
	Name        string `json:"name"`
	Label       string `json:"label"`
	Required    bool   `json:"required"`
	Placeholder string `json:"placeholder"`
	Default     string `json:"default"`
}

type GetChannelConfigsResp struct {
	Name    string      `json:"name"`
	Label   string      `json:"label"`
	Configs []FormField `json:"configs"`
}

type IDReq struct {
	ID int64 `json:"id" validate:"required"`
}

type IDStatusReq struct {
	ID     int64 `json:"id" validate:"required"`
	Status bool  `json:"status"`
}

type InfoResp struct {
	ID          int64  `json:"id"`
	AgentNo     string `json:"agent_no"`     // 编号
	AgentSecret string `json:"agent_secret"` // 密钥
	Name        string `json:"name"`         // 联系人姓名
	Phone       string `json:"phone"`        // 手机号
	Email       string `json:"email"`        // 邮箱
	Status      bool   `json:"status"`       // 状态（true=启用，false=禁用）
	CreatedAt   string `json:"created_at"`   // 创建时间
	UpdatedAt   string `json:"updated_at"`   // 更新时间
}

type LoginReq struct {
	Email    string `json:"email" validate:"email"`
	Password string `json:"password" validate:"required"`
}

type LoginResp struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	Token     string `json:"token"`
	ExpiresIn int64  `json:"expires_in"`
}

type PaginationReq struct {
	Page int `json:"page,default=1"`
	Size int `json:"size,default=10"`
}

type RegisterReq struct {
	Email    string `json:"email" validate:"email"`
	Password string `json:"password" validate:"required"`
	Phone    string `json:"phone,optional"`
}

type ResetSecretResp struct {
	AgentSecret string `json:"agent_secret"`
}

type TemplateCreateReq struct {
	ChannelID  int64  `json:"channel_id"`
	Code       string `json:"code"`
	VendorCode string `json:"vendor_code,optional,omitempty"`
	Signature  string `json:"signature,optional,omitempty"`
	Content    string `json:"content"`
	Status     bool   `json:"status"`
}

type TemplateItemResp struct {
	ID         int64  `json:"id"`
	AgentID    int64  `json:"agent_id"`
	ChannelID  int64  `json:"channel_id"`
	Code       string `json:"code"`
	VendorCode string `json:"vendor_code"`
	Signature  string `json:"signature"`
	Content    string `json:"content"`
	Status     bool   `json:"status"`
	UsedCount  int64  `json:"used_count"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}

type TemplateQueryReq struct {
	PaginationReq
	ID       int64  `json:"id,optional"`
	Keywords string `json:"keywords,optional"`
}

type TemplateQueryResp struct {
	Total int64              `json:"total"`
	Data  []TemplateItemResp `json:"data"`
}

type TemplateUpdateReq struct {
	ID         int64   `json:"id"`
	ChannelID  *int64  `json:"channel_id"`
	VendorCode *string `json:"vendor_code,optional,omitempty"`
	Signature  *string `json:"signature,optional,omitempty"`
	Content    *string `json:"content,optional,omitempty"`
	Status     *bool   `json:"status,optional,omitempty"`
}
