// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: gateway.proto

package server

import (
	"context"

	"chihqiang/msgbox-go/services/gateway/rpc/internal/logic"
	"chihqiang/msgbox-go/services/gateway/rpc/internal/svc"
	"chihqiang/msgbox-go/services/gateway/rpc/pb/rpc"
)

type GatewayServer struct {
	svcCtx *svc.ServiceContext
	rpc.UnimplementedGatewayServer
}

func NewGatewayServer(svcCtx *svc.ServiceContext) *GatewayServer {
	return &GatewayServer{
		svcCtx: svcCtx,
	}
}

func (s *GatewayServer) Send(ctx context.Context, in *rpc.SendRequest) (*rpc.SendResponse, error) {
	l := logic.NewSendLogic(ctx, s.svcCtx)
	return l.Send(in)
}
